# Generated by Django 3.2.19 on 2023-07-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
